---
- name: manager
  hosts: manager
  user: root

  roles:
  - docker
# for consul
#  - consul
  - etcd
  - swarm-manager
  - swarm-node

  tasks:
  - service: name=firewalld state=restarted
    when: firewalld is defined
