---
- name: k8smaster
  hosts: manager
  user: root
  vars:
  - master: 192.168.200.1
  - network: 10.1.0.0/16
    # Backend type
    # UDP encapsulate:  {"Type": "udp", "Port": 7890}
    # VXLAN:            {"Type": "vxlan", "VNI": 1, Port: 4789 }
    # Host Gateway:     {"Type": "host-gw" }
#  - backend: '{"Type": "vxlan", "VNI": 1, "UDPCSum": true}'
  - backend: '{"Type": "vxlan", "VNI": 1}'
##  - backend: '{"Type": "host-gw"}'
#  - backend: '{"Type": "host-gw"}'
  - interface: enp0s8
  - systemd_path: /lib/systemd/system
  roles:
  - config
  - k8s-etcd
  - flannel
  - k8s-master
  - k8s-worker

- name: k8sworkers
  hosts: nodes
  vars:
  - master: 192.168.200.1
  - interface: enp0s8
  - systemd_path: /lib/systemd/system
  roles:
  - config
  - flannel
  - k8s-worker
