---
- name: manager
  hosts: manager
  user: root

  roles:
  - { role: etcd, cluster: 'native' }
  - { role: docker, native_cluster: True }

  tasks:
  - service: name=firewalld state=restarted
    when: firewalld is defined

- name: nodes
  hosts: nodes
  user: root

  roles:
  - { role: docker, native_cluster: True}

  tasks:
  - service: name=firewalld state=restarted
    when: firewalld is defined

