- get_url: url=https://github.com/coreos/etcd/releases/download/v{{etcd_ver}}/etcd-v{{etcd_ver}}-linux-amd64.tar.gz dest=/tmp validate_certs=False
  environment: proxy_env
- unarchive: src=/tmp/etcd-v{{etcd_ver}}-linux-amd64.tar.gz dest=/tmp copy=no
- command: cp /tmp/etcd-v{{etcd_ver}}-linux-amd64/etcd /usr/local/bin
- command: cp /tmp/etcd-v{{etcd_ver}}-linux-amd64/etcdctl /usr/local/bin

