---
- name: Check etcd install
  stat: path=/usr/local/bin/etcd
  register: check_etch_install

- include: install.yml
  when: check_etch_install.stat.exists == False

- file: path=/var/lib/etcd state=directory mode=0755

- template: src=etcd.service.j2 dest={{systemd_path}}/etcd.service

- name: Load copied systemd file
  command: systemctl daemon-reload

- name: Start etcd container as systemd service
  service: name=etcd.service state=running enabled=yes

- include: firewalld.yml
  when: firewalld is defined

- include: ufw.yml
  when: ufw is defined
