---
- command: /usr/local/bin/etcd --version
  register: chk_etcd
  ignore_errors: yes

- include: install.yml
  when: (chk_etcd.rc != 0) or (chk_etcd.stdout.find("etcd Version{{':'}} {{etcd_ver}}"))

- file: path=/var/lib/etcd state=directory mode=0755

- template: src=etcd.service.{{cluster}}.j2 dest={{systemd_path}}/etcd.service

- name: Load copied systemd file
  command: systemctl daemon-reload

- name: Start etcd container as systemd service
  service: name=etcd.service state=restarted enabled=yes

- command: etcdctl ls /
  register: res
  until: res.rc == 0
  retries: 6
  delay: 10

- include: firewalld.yml
  when: firewalld is defined

- include: ufw.yml
  when: ufw is defined
