---
- name: Check docker installed
  stat: path=/usr/bin/docker
  register: check_docker_install

- name: Install docker
  shell: curl -L -k https://get.docker.com/ | sh
  when: check_docker_install.stat.exists == False
  environment: proxy_env

- name: Create systemd service
  template: src="docker.service.j2" dest="{{systemd_path}}/docker.service"

- name: Create default environment for docker service
  template: src="docker.j2" dest="/etc/default/docker"

- name: Reload systemd file
  command: systemctl daemon-reload

- name: Docker service start
  service: name=docker state=restarted enabled=yes

- command: docker info
  register: docker_info
  until: docker_info.rc == 0
  retries: 3
  delay: 5
