---
- name: Check swarm manage container
  command: docker inspect swarm_manage
  register: check_manage
  ignore_errors: yes

- name: Pull swarm image
  command: docker pull swarm
  when: check_manage.rc !=0 

#- name: Set http_proxy for swarm
#  set_fact:
#    swarm_env: -e http_proxy={{proxy_env.http_proxy}} -e no_proxy={{proxy_env.no_proxy}}
#  when: http_proxy is defined and  http_proxy != None

- name: Create swarm manage container
  command: /usr/bin/docker create --name swarm_manage -p 4000:4000 swarm -debug manage -H :4000 --replication --advertise {{hostvars[inventory_hostname]["ansible_"+manage_if]["ipv4"]["address"]}}:4000 {{cluster_store}}
  when: check_manage.rc !=0

- name: Copy systemd service
  copy: src=docker-swarm-manage.service dest={{systemd_path}}/docker-swarm-manage.service

- name: Reload systemd file
  command: systemctl daemon-reload

- name: Run swarm manage container
  service: name=docker-swarm-manage.service state=running enabled=yes

- firewalld: port=2376/tcp permanent=true state=enabled
  when: firewalld is defined

- ufw: rule=allow proto=tcp port=2375
  when: ufw is defined
